In [1]:
import numpy as np

array1 = [[11,12,13,14],
          [22,23,24,25],
          [33,34,35,36]]

array1_new = np.array(array1)
print(array1_new)

[[11 12 13 14]
 [22 23 24 25]
 [33 34 35 36]]


In [2]:
x=[1,2,3,4]

array2=np.array(x)
print(array2)

[1 2 3 4]


shape and ndim


In [3]:
print(array1_new.ndim)

2


In [4]:
print(array1_new.shape)

(3, 4)


np.arrange() and np.resize()

In [5]:
print(array1_new)

[[11 12 13 14]
 [22 23 24 25]
 [33 34 35 36]]


In [6]:
print(array1_new.shape)

(3, 4)


In [7]:
array2=array1_new.reshape(4,3)
print(array2)

[[11 12 13]
 [14 22 23]
 [24 25 33]
 [34 35 36]]


In [8]:
array2=array1_new.reshape(6,2)
print(array2)

[[11 12]
 [13 14]
 [22 23]
 [24 25]
 [33 34]
 [35 36]]


In [9]:
array2=array1_new.reshape(1,12)
print(array2)

[[11 12 13 14 22 23 24 25 33 34 35 36]]


In [10]:
array=np.arange(-10,10,2)
print(array,array.ndim,array.shape)

[-10  -8  -6  -4  -2   0   2   4   6   8] 1 (10,)


In [11]:
array1=array.reshape(-1,1)
print(array1)

[[-10]
 [ -8]
 [ -6]
 [ -4]
 [ -2]
 [  0]
 [  2]
 [  4]
 [  6]
 [  8]]


In [12]:
array1=array.reshape(1,-1)
print(array1)

[[-10  -8  -6  -4  -2   0   2   4   6   8]]


Array Creation Routines

In [13]:
import numpy as np
x = np.empty((3,2),dtype = int)
print(x)

[[-9223231303063230333  7432766889844192047]
 [       2224334254640        2224334254680]
 [                  19                    4]]


In [14]:
x = np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [15]:
x = np.zeros((5,3),dtype = float)
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
x = np.zeros((5,3),dtype = float)
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
x = np.ones((5,3),dtype = float)
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Indexing & Slicing

In [18]:
array=np.random.randint(0,100,(10,5))
print(array)

[[93  7 61  0 44]
 [86 81 31 66 63]
 [63 12 42 31 90]
 [88 13 87 57 56]
 [93 58 42 71 62]
 [47 71 68  7 76]
 [27  5 56 52 12]
 [51 11  2 85 95]
 [89 95  3 60  5]
 [37 75 76 94 50]]


In [19]:
array1=np.random.randint(0,100,(4,3))
array2=np.random.randint(0,100,(4,3))

array3 = array1 + array2
print('array1:',array1)
print('array2:',array2)
print('array3:',array3)

array1: [[93 14 69]
 [95 26 74]
 [46 68 14]
 [74 14 40]]
array2: [[13 16 77]
 [61  0 69]
 [73 29 75]
 [69 45 76]]
array3: [[106  30 146]
 [156  26 143]
 [119  97  89]
 [143  59 116]]


In [20]:
array1=np.random.randint(0,100,(4,3))

array2=array1/10

print('array1:',array1)
print('array2:',array2)

array1: [[11 95 87]
 [54 89 40]
 [41 89 50]
 [59 95  1]]
array2: [[1.1 9.5 8.7]
 [5.4 8.9 4. ]
 [4.1 8.9 5. ]
 [5.9 9.5 0.1]]


In [21]:
array1=np.random.randint(0,100,(4,3))
array2=np.random.randint(0,100,(3,5))

print('array1:',array1)
print('array2:',array2)

array4=np.matmul(array1,array2)

print('array4:',array4)

array1: [[73 44 28]
 [14 14 87]
 [44 50 33]
 [88 96 86]]
array2: [[39 92 72 53 78]
 [77 76 63 83 29]
 [32 33 35 54 38]]
array4: [[ 7131 10984  9008  9033  8034]
 [ 4408  5223  4935  6602  4804]
 [ 6622  8937  7473  8264  6136]
 [13576 18230 15394 17276 12916]]


In [22]:
array=np.random.randint(0,100,(5,7))
print(array)

[[63 60 67 55 53 53 95]
 [36 22 85 75 82 72 85]
 [16 25 14 33  1 31 90]
 [42 97  8 95  7 60 15]
 [10 44 77 83 65 48 58]]


In [23]:
print(np.max(array))

97


In [24]:
print(np.argmax(array))

22


In [25]:
print(np.max(array,axis=0))

[63 97 85 95 82 72 95]


In [26]:
print(np.argmax(array,axis=0))

[0 3 1 3 1 1 0]


In [27]:
print(np.max(array,axis=1))

[95 85 90 97 83]


In [28]:
print(np.argmax(array,axis=1))

[6 2 6 1 3]


In [29]:
array=np.random.randint(0,100,(5,10))
print(array)

[[75 99 47 37 44 58 69 47 11 13]
 [ 9 31 26 61 12 93 87 71 37 95]
 [21 34 97 46 77 11  7 33 27 27]
 [92 67  5 97  5  5 57 43 11 84]
 [18 22 26 78 83 26 96 26 62 65]]


In [30]:
print(array[2,3])

46


In [31]:
print(array[0:2,0:4])

[[75 99 47 37]
 [ 9 31 26 61]]


In [32]:
print(array[:,0:4])

[[75 99 47 37]
 [ 9 31 26 61]
 [21 34 97 46]
 [92 67  5 97]
 [18 22 26 78]]


In [33]:
print(array[:,4])

[44 12 77  5 83]


In [34]:
print(array[:2,:])

[[75 99 47 37 44 58 69 47 11 13]
 [ 9 31 26 61 12 93 87 71 37 95]]


In [35]:
import pandas as pd

dataset=pd.read_csv('student-marks.csv')

In [36]:
print(dataset)

        Name  Maths  Physics  Chemistry
0       John     45       22         98
1    William     44       23          2
2      Henry     22       89         35
3      Chris     88       55         23
4       Jack     45       89         45
5   Stephane     64       45         48
6     Harald     12       12         12
7     Hearmy     78       94         65
8     Sinsel     98       95         23
9     George     45       65         89
10     James     64       32         26
11      Jade     23       78         47
12     Tommy     45       98         14
13     Yonus     78       45         44
14     Randy     95       12         84
15       Rex     31       95         98
16    Tucsan     77       32         56
17     Amell     87       78         34
18       Vin     65       45         78
19    Hector     32       12         78


In [37]:
dataset=pd.read_csv('student-marks.csv').values
print(dataset,dataset.ndim,dataset.shape)

[['John' 45 22 98]
 ['William' 44 23 2]
 ['Henry' 22 89 35]
 ['Chris' 88 55 23]
 ['Jack' 45 89 45]
 ['Stephane' 64 45 48]
 ['Harald' 12 12 12]
 ['Hearmy' 78 94 65]
 ['Sinsel' 98 95 23]
 ['George' 45 65 89]
 ['James' 64 32 26]
 ['Jade' 23 78 47]
 ['Tommy' 45 98 14]
 ['Yonus' 78 45 44]
 ['Randy' 95 12 84]
 ['Rex' 31 95 98]
 ['Tucsan' 77 32 56]
 ['Amell' 87 78 34]
 ['Vin' 65 45 78]
 ['Hector' 32 12 78]] 2 (20, 4)


In [38]:
import numpy as np
avg=np.mean(dataset[:,1:4],axis=1)
print(avg)

[55.0 23.0 48.666666666666664 55.333333333333336 59.666666666666664
 52.333333333333336 12.0 79.0 72.0 66.33333333333333 40.666666666666664
 49.333333333333336 52.333333333333336 55.666666666666664
 63.666666666666664 74.66666666666667 55.0 66.33333333333333
 62.666666666666664 40.666666666666664]


In [39]:
def findGrade(mark):
    if(mark>=0 and mark<35):
        grade = 'F'
    elif(mark>=35 and mark<45):
        grade = 'S'
    elif(mark>=45 and mark<65):
        grade = 'C'
    elif(mark>=65 and mark<75):
        grade = 'B'
    elif(mark>=75 and mark<=100):
        grade = 'A'
    return grade

In [40]:
for i in dataset[:,1]:
    print(findGrade(i))

C
S
F
A
C
C
F
A
A
C
C
F
C
A
A
F
A
A
B
F


In [41]:
mathsGrades = np.array([findGrade(i) for i in dataset[:,1]])

print(mathsGrades)
mathsGrades=mathsGrades.reshape(-1,1)
print(mathsGrades)

['C' 'S' 'F' 'A' 'C' 'C' 'F' 'A' 'A' 'C' 'C' 'F' 'C' 'A' 'A' 'F' 'A' 'A'
 'B' 'F']
[['C']
 ['S']
 ['F']
 ['A']
 ['C']
 ['C']
 ['F']
 ['A']
 ['A']
 ['C']
 ['C']
 ['F']
 ['C']
 ['A']
 ['A']
 ['F']
 ['A']
 ['A']
 ['B']
 ['F']]


In [42]:
phyGrades=np.array([findGrade(i) for i in dataset[:,1]])
phyGrades=phyGrades.reshape(-1,1)
print(phyGrades)

[['C']
 ['S']
 ['F']
 ['A']
 ['C']
 ['C']
 ['F']
 ['A']
 ['A']
 ['C']
 ['C']
 ['F']
 ['C']
 ['A']
 ['A']
 ['F']
 ['A']
 ['A']
 ['B']
 ['F']]


In [43]:
chemGrades=np.array([findGrade(i) for i in dataset[:,3]])
chemGrades=chemGrades.reshape(-1,1)
print(chemGrades)

[['A']
 ['F']
 ['S']
 ['F']
 ['C']
 ['C']
 ['F']
 ['B']
 ['F']
 ['A']
 ['F']
 ['C']
 ['F']
 ['S']
 ['A']
 ['A']
 ['C']
 ['F']
 ['A']
 ['A']]


In [44]:
avg=avg.reshape(-1,1).reshape(-1,1)
print(avg)

[[55.0]
 [23.0]
 [48.666666666666664]
 [55.333333333333336]
 [59.666666666666664]
 [52.333333333333336]
 [12.0]
 [79.0]
 [72.0]
 [66.33333333333333]
 [40.666666666666664]
 [49.333333333333336]
 [52.333333333333336]
 [55.666666666666664]
 [63.666666666666664]
 [74.66666666666667]
 [55.0]
 [66.33333333333333]
 [62.666666666666664]
 [40.666666666666664]]


In [45]:
print(dataset)

[['John' 45 22 98]
 ['William' 44 23 2]
 ['Henry' 22 89 35]
 ['Chris' 88 55 23]
 ['Jack' 45 89 45]
 ['Stephane' 64 45 48]
 ['Harald' 12 12 12]
 ['Hearmy' 78 94 65]
 ['Sinsel' 98 95 23]
 ['George' 45 65 89]
 ['James' 64 32 26]
 ['Jade' 23 78 47]
 ['Tommy' 45 98 14]
 ['Yonus' 78 45 44]
 ['Randy' 95 12 84]
 ['Rex' 31 95 98]
 ['Tucsan' 77 32 56]
 ['Amell' 87 78 34]
 ['Vin' 65 45 78]
 ['Hector' 32 12 78]]


In [46]:
dataset=np.append(dataset,mathsGrades,axis=1)
print(dataset)

[['John' 45 22 98 'C']
 ['William' 44 23 2 'S']
 ['Henry' 22 89 35 'F']
 ['Chris' 88 55 23 'A']
 ['Jack' 45 89 45 'C']
 ['Stephane' 64 45 48 'C']
 ['Harald' 12 12 12 'F']
 ['Hearmy' 78 94 65 'A']
 ['Sinsel' 98 95 23 'A']
 ['George' 45 65 89 'C']
 ['James' 64 32 26 'C']
 ['Jade' 23 78 47 'F']
 ['Tommy' 45 98 14 'C']
 ['Yonus' 78 45 44 'A']
 ['Randy' 95 12 84 'A']
 ['Rex' 31 95 98 'F']
 ['Tucsan' 77 32 56 'A']
 ['Amell' 87 78 34 'A']
 ['Vin' 65 45 78 'B']
 ['Hector' 32 12 78 'F']]


In [47]:
dataset=np.append(dataset,phyGrades,axis=1)
print(dataset)

[['John' 45 22 98 'C' 'C']
 ['William' 44 23 2 'S' 'S']
 ['Henry' 22 89 35 'F' 'F']
 ['Chris' 88 55 23 'A' 'A']
 ['Jack' 45 89 45 'C' 'C']
 ['Stephane' 64 45 48 'C' 'C']
 ['Harald' 12 12 12 'F' 'F']
 ['Hearmy' 78 94 65 'A' 'A']
 ['Sinsel' 98 95 23 'A' 'A']
 ['George' 45 65 89 'C' 'C']
 ['James' 64 32 26 'C' 'C']
 ['Jade' 23 78 47 'F' 'F']
 ['Tommy' 45 98 14 'C' 'C']
 ['Yonus' 78 45 44 'A' 'A']
 ['Randy' 95 12 84 'A' 'A']
 ['Rex' 31 95 98 'F' 'F']
 ['Tucsan' 77 32 56 'A' 'A']
 ['Amell' 87 78 34 'A' 'A']
 ['Vin' 65 45 78 'B' 'B']
 ['Hector' 32 12 78 'F' 'F']]


In [48]:
dataset=np.append(dataset,avg,axis=1)
print(dataset)

[['John' 45 22 98 'C' 'C' 55.0]
 ['William' 44 23 2 'S' 'S' 23.0]
 ['Henry' 22 89 35 'F' 'F' 48.666666666666664]
 ['Chris' 88 55 23 'A' 'A' 55.333333333333336]
 ['Jack' 45 89 45 'C' 'C' 59.666666666666664]
 ['Stephane' 64 45 48 'C' 'C' 52.333333333333336]
 ['Harald' 12 12 12 'F' 'F' 12.0]
 ['Hearmy' 78 94 65 'A' 'A' 79.0]
 ['Sinsel' 98 95 23 'A' 'A' 72.0]
 ['George' 45 65 89 'C' 'C' 66.33333333333333]
 ['James' 64 32 26 'C' 'C' 40.666666666666664]
 ['Jade' 23 78 47 'F' 'F' 49.333333333333336]
 ['Tommy' 45 98 14 'C' 'C' 52.333333333333336]
 ['Yonus' 78 45 44 'A' 'A' 55.666666666666664]
 ['Randy' 95 12 84 'A' 'A' 63.666666666666664]
 ['Rex' 31 95 98 'F' 'F' 74.66666666666667]
 ['Tucsan' 77 32 56 'A' 'A' 55.0]
 ['Amell' 87 78 34 'A' 'A' 66.33333333333333]
 ['Vin' 65 45 78 'B' 'B' 62.666666666666664]
 ['Hector' 32 12 78 'F' 'F' 40.666666666666664]]


In [49]:
np.save('new-dataset',dataset)

In [50]:
np.savetxt("dataset-new.csv",dataset,delimiter=",")

TypeError: Mismatch between array dtype ('object') and format specifier ('%.18e,%.18e,%.18e,%.18e,%.18e,%.18e,%.18e')

In [57]:
df=pd.DataFrame(data=dataset)
print(df)

           0   1   2   3  4  5          6
0       John  45  22  98  C  C       55.0
1    William  44  23   2  S  S       23.0
2      Henry  22  89  35  F  F  48.666667
3      Chris  88  55  23  A  A  55.333333
4       Jack  45  89  45  C  C  59.666667
5   Stephane  64  45  48  C  C  52.333333
6     Harald  12  12  12  F  F       12.0
7     Hearmy  78  94  65  A  A       79.0
8     Sinsel  98  95  23  A  A       72.0
9     George  45  65  89  C  C  66.333333
10     James  64  32  26  C  C  40.666667
11      Jade  23  78  47  F  F  49.333333
12     Tommy  45  98  14  C  C  52.333333
13     Yonus  78  45  44  A  A  55.666667
14     Randy  95  12  84  A  A  63.666667
15       Rex  31  95  98  F  F  74.666667
16    Tucsan  77  32  56  A  A       55.0
17     Amell  87  78  34  A  A  66.333333
18       Vin  65  45  78  B  B  62.666667
19    Hector  32  12  78  F  F  40.666667


In [66]:
df=pd.DataFrame(data=dataset,columns=["name","maths","phy","chem","m-grade","p-grade","c-grade","avg"])
print(df)



ValueError: Shape of passed values is (20, 7), indices imply (20, 8)