In [1]:
import numpy as np

array1 = [[11,12,13,14],
          [22,23,24,25],
          [33,34,35,36]]

array1_new = np.array(array1)
print(array1_new)

[[11 12 13 14]
 [22 23 24 25]
 [33 34 35 36]]


In [2]:
x=[1,2,3,4]

array2=np.array(x)
print(array2)

[1 2 3 4]


shape and ndim


In [3]:
print(array1_new.ndim)

2


In [4]:
print(array1_new.shape)

(3, 4)


np.arrange() and np.resize()

In [5]:
print(array1_new)

[[11 12 13 14]
 [22 23 24 25]
 [33 34 35 36]]


In [6]:
print(array1_new.shape)

(3, 4)


In [7]:
array2=array1_new.reshape(4,3)
print(array2)

[[11 12 13]
 [14 22 23]
 [24 25 33]
 [34 35 36]]


In [8]:
array2=array1_new.reshape(6,2)
print(array2)

[[11 12]
 [13 14]
 [22 23]
 [24 25]
 [33 34]
 [35 36]]


In [9]:
array2=array1_new.reshape(1,12)
print(array2)

[[11 12 13 14 22 23 24 25 33 34 35 36]]


In [10]:
array=np.arange(-10,10,2)
print(array,array.ndim,array.shape)

[-10  -8  -6  -4  -2   0   2   4   6   8] 1 (10,)


In [11]:
array1=array.reshape(-1,1)
print(array1)

[[-10]
 [ -8]
 [ -6]
 [ -4]
 [ -2]
 [  0]
 [  2]
 [  4]
 [  6]
 [  8]]


In [12]:
array1=array.reshape(1,-1)
print(array1)

[[-10  -8  -6  -4  -2   0   2   4   6   8]]


Array Creation Routines

In [13]:
import numpy as np
x = np.empty((3,2),dtype = int)
print(x)

[[ 69530937880412407 379147854587168067]
 [433758724448257541  69530937880412407]
 [379147854587168067 433758724448257541]]


In [14]:
x = np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [15]:
x = np.zeros((5,3),dtype = float)
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
x = np.zeros((5,3),dtype = float)
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
x = np.ones((5,3),dtype = float)
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Indexing & Slicing

In [18]:
array=np.random.randint(0,100,(10,5))
print(array)

[[16  8 72 70 30]
 [13 66 97 48  4]
 [72  6 28 33 47]
 [65 54 88 67 64]
 [11  0 48 50 50]
 [81 33 54 85 60]
 [79 74 96 93  0]
 [86 45 80 68 19]
 [12 44 30  0 30]
 [20 93 47 70 84]]


In [19]:
array1=np.random.randint(0,100,(4,3))
array2=np.random.randint(0,100,(4,3))

array3 = array1 + array2
print('array1:',array1)
print('array2:',array2)
print('array3:',array3)

array1: [[39 82 21]
 [33 71 88]
 [66 85 69]
 [95 12 42]]
array2: [[91 89 98]
 [29 69 40]
 [44 62 11]
 [44 23 92]]
array3: [[130 171 119]
 [ 62 140 128]
 [110 147  80]
 [139  35 134]]


In [20]:
array1=np.random.randint(0,100,(4,3))

array2=array1/10

print('array1:',array1)
print('array2:',array2)

array1: [[76 54 44]
 [91  2 95]
 [30 54 39]
 [20 61 88]]
array2: [[7.6 5.4 4.4]
 [9.1 0.2 9.5]
 [3.  5.4 3.9]
 [2.  6.1 8.8]]


In [21]:
array1=np.random.randint(0,100,(4,3))
array2=np.random.randint(0,100,(3,5))

print('array1:',array1)
print('array2:',array2)

array4=np.matmul(array1,array2)

print('array4:',array4)

array1: [[71 60 56]
 [82 73 30]
 [15 56 87]
 [46 19  8]]
array2: [[92 36 22  2 32]
 [95 66 69 48 76]
 [86 48 19 30 28]]
array4: [[17048  9204  6766  4702  8400]
 [17059  9210  7411  4568  9012]
 [14182  8412  5847  5328  7172]
 [ 6725  3294  2475  1244  3140]]


In [22]:
array=np.random.randint(0,100,(5,7))
print(array)

[[ 0  1 72 19 81 43 66]
 [22 23 61 70 67 89 59]
 [55 61 28 69 72 22  4]
 [91 74 17 50 58 32  5]
 [69 43  8 96 64 48 49]]


In [23]:
print(np.max(array))

96


In [24]:
print(np.argmax(array))

31


In [25]:
print(np.max(array,axis=0))

[91 74 72 96 81 89 66]


In [26]:
print(np.argmax(array,axis=0))

[3 3 0 4 0 1 0]


In [27]:
print(np.max(array,axis=1))

[81 89 72 91 96]


In [28]:
print(np.argmax(array,axis=1))

[4 5 4 0 3]


In [29]:
array=np.random.randint(0,100,(5,10))
print(array)

[[ 5 52  7 95 69 32 70 78 89 15]
 [86 32 59 40 43 59 49 86 72 95]
 [18 11 24 46 62 45  4 81 37 10]
 [37 56 86 12 36 52 89 54 59 60]
 [72 96 44 47 60 30 20 94 78 85]]


In [30]:
print(array[2,3])

46


In [31]:
print(array[0:2,0:4])

[[ 5 52  7 95]
 [86 32 59 40]]


In [32]:
print(array[:,0:4])

[[ 5 52  7 95]
 [86 32 59 40]
 [18 11 24 46]
 [37 56 86 12]
 [72 96 44 47]]


In [33]:
print(array[:,4])

[69 43 62 36 60]


In [34]:
print(array[:2,:])

[[ 5 52  7 95 69 32 70 78 89 15]
 [86 32 59 40 43 59 49 86 72 95]]


In [35]:
import pandas as pd

dataset=pd.read_csv('student-marks.csv')

In [36]:
print(dataset)

        Name  Maths  Physics  Chemistry
0       John     45       22         98
1    William     44       23          2
2      Henry     22       89         35
3      Chris     88       55         23
4       Jack     45       89         45
5   Stephane     64       45         48
6     Harald     12       12         12
7     Hearmy     78       94         65
8     Sinsel     98       95         23
9     George     45       65         89
10     James     64       32         26
11      Jade     23       78         47
12     Tommy     45       98         14
13     Yonus     78       45         44
14     Randy     95       12         84
15       Rex     31       95         98
16    Tucsan     77       32         56
17     Amell     87       78         34
18       Vin     65       45         78
19    Hector     32       12         78


In [37]:
dataset=pd.read_csv('student-marks.csv').values
print(dataset,dataset.ndim,dataset.shape)

[['John' 45 22 98]
 ['William' 44 23 2]
 ['Henry' 22 89 35]
 ['Chris' 88 55 23]
 ['Jack' 45 89 45]
 ['Stephane' 64 45 48]
 ['Harald' 12 12 12]
 ['Hearmy' 78 94 65]
 ['Sinsel' 98 95 23]
 ['George' 45 65 89]
 ['James' 64 32 26]
 ['Jade' 23 78 47]
 ['Tommy' 45 98 14]
 ['Yonus' 78 45 44]
 ['Randy' 95 12 84]
 ['Rex' 31 95 98]
 ['Tucsan' 77 32 56]
 ['Amell' 87 78 34]
 ['Vin' 65 45 78]
 ['Hector' 32 12 78]] 2 (20, 4)


In [38]:
import numpy as np
avg=np.mean(dataset[:,1:4],axis=1)
print(avg)

[55.0 23.0 48.666666666666664 55.333333333333336 59.666666666666664
 52.333333333333336 12.0 79.0 72.0 66.33333333333333 40.666666666666664
 49.333333333333336 52.333333333333336 55.666666666666664
 63.666666666666664 74.66666666666667 55.0 66.33333333333333
 62.666666666666664 40.666666666666664]


In [39]:
def findGrade(mark):
    if(mark>=0 and mark<35):
        grade = 'F'
    elif(mark>=35 and mark<45):
        grade = 'S'
    elif(mark>=45 and mark<65):
        grade = 'C'
    elif(mark>=65 and mark<75):
        grade = 'B'
    elif(mark>=75 and mark<=100):
        grade = 'A'
    return grade

In [45]:
for i in dataset[:,1]:
    print(findGrade(i))

C
S
F
A
C
C
F
A
A
C
C
F
C
A
A
F
A
A
B
F


In [43]:
mathsGrades = np.array([findGrade(i) for i in dataset[:,1]])

print(mathsGrades)
mathsGrades=mathsGrades.reshape(-1,1)
print(mathsGrades)

['C' 'S' 'F' 'A' 'C' 'C' 'F' 'A' 'A' 'C' 'C' 'F' 'C' 'A' 'A' 'F' 'A' 'A'
 'B' 'F']
[['C']
 ['S']
 ['F']
 ['A']
 ['C']
 ['C']
 ['F']
 ['A']
 ['A']
 ['C']
 ['C']
 ['F']
 ['C']
 ['A']
 ['A']
 ['F']
 ['A']
 ['A']
 ['B']
 ['F']]


In [46]:
phyGrades=np.array([findGrade(i) for i in dataset[:,1]])
phyGrades=phyGrades.reshape(-1,1)
print(phyGrades)

[['C']
 ['S']
 ['F']
 ['A']
 ['C']
 ['C']
 ['F']
 ['A']
 ['A']
 ['C']
 ['C']
 ['F']
 ['C']
 ['A']
 ['A']
 ['F']
 ['A']
 ['A']
 ['B']
 ['F']]


In [48]:
chemGrades=np.array([findGrade(i) for i in dataset[:,3]])
chemGrades=chemGrades.reshape(-1,1)
print(chemGrades)

[['A']
 ['F']
 ['S']
 ['F']
 ['C']
 ['C']
 ['F']
 ['B']
 ['F']
 ['A']
 ['F']
 ['C']
 ['F']
 ['S']
 ['A']
 ['A']
 ['C']
 ['F']
 ['A']
 ['A']]


In [49]:
avg=avg.reshape(-1,1).reshape(-1,1)
print(avg)

[[55.0]
 [23.0]
 [48.666666666666664]
 [55.333333333333336]
 [59.666666666666664]
 [52.333333333333336]
 [12.0]
 [79.0]
 [72.0]
 [66.33333333333333]
 [40.666666666666664]
 [49.333333333333336]
 [52.333333333333336]
 [55.666666666666664]
 [63.666666666666664]
 [74.66666666666667]
 [55.0]
 [66.33333333333333]
 [62.666666666666664]
 [40.666666666666664]]


In [50]:
print(dataset)

[['John' 45 22 98]
 ['William' 44 23 2]
 ['Henry' 22 89 35]
 ['Chris' 88 55 23]
 ['Jack' 45 89 45]
 ['Stephane' 64 45 48]
 ['Harald' 12 12 12]
 ['Hearmy' 78 94 65]
 ['Sinsel' 98 95 23]
 ['George' 45 65 89]
 ['James' 64 32 26]
 ['Jade' 23 78 47]
 ['Tommy' 45 98 14]
 ['Yonus' 78 45 44]
 ['Randy' 95 12 84]
 ['Rex' 31 95 98]
 ['Tucsan' 77 32 56]
 ['Amell' 87 78 34]
 ['Vin' 65 45 78]
 ['Hector' 32 12 78]]


In [51]:
dataset=np.append(dataset,mathsGrades,axis=1)
print(dataset)

[['John' 45 22 98 'C']
 ['William' 44 23 2 'S']
 ['Henry' 22 89 35 'F']
 ['Chris' 88 55 23 'A']
 ['Jack' 45 89 45 'C']
 ['Stephane' 64 45 48 'C']
 ['Harald' 12 12 12 'F']
 ['Hearmy' 78 94 65 'A']
 ['Sinsel' 98 95 23 'A']
 ['George' 45 65 89 'C']
 ['James' 64 32 26 'C']
 ['Jade' 23 78 47 'F']
 ['Tommy' 45 98 14 'C']
 ['Yonus' 78 45 44 'A']
 ['Randy' 95 12 84 'A']
 ['Rex' 31 95 98 'F']
 ['Tucsan' 77 32 56 'A']
 ['Amell' 87 78 34 'A']
 ['Vin' 65 45 78 'B']
 ['Hector' 32 12 78 'F']]


In [52]:
dataset=np.append(dataset,phyGrades,axis=1)
print(dataset)

[['John' 45 22 98 'C' 'C']
 ['William' 44 23 2 'S' 'S']
 ['Henry' 22 89 35 'F' 'F']
 ['Chris' 88 55 23 'A' 'A']
 ['Jack' 45 89 45 'C' 'C']
 ['Stephane' 64 45 48 'C' 'C']
 ['Harald' 12 12 12 'F' 'F']
 ['Hearmy' 78 94 65 'A' 'A']
 ['Sinsel' 98 95 23 'A' 'A']
 ['George' 45 65 89 'C' 'C']
 ['James' 64 32 26 'C' 'C']
 ['Jade' 23 78 47 'F' 'F']
 ['Tommy' 45 98 14 'C' 'C']
 ['Yonus' 78 45 44 'A' 'A']
 ['Randy' 95 12 84 'A' 'A']
 ['Rex' 31 95 98 'F' 'F']
 ['Tucsan' 77 32 56 'A' 'A']
 ['Amell' 87 78 34 'A' 'A']
 ['Vin' 65 45 78 'B' 'B']
 ['Hector' 32 12 78 'F' 'F']]


In [53]:
dataset=np.append(dataset,avg,axis=1)
print(dataset)

[['John' 45 22 98 'C' 'C' 55.0]
 ['William' 44 23 2 'S' 'S' 23.0]
 ['Henry' 22 89 35 'F' 'F' 48.666666666666664]
 ['Chris' 88 55 23 'A' 'A' 55.333333333333336]
 ['Jack' 45 89 45 'C' 'C' 59.666666666666664]
 ['Stephane' 64 45 48 'C' 'C' 52.333333333333336]
 ['Harald' 12 12 12 'F' 'F' 12.0]
 ['Hearmy' 78 94 65 'A' 'A' 79.0]
 ['Sinsel' 98 95 23 'A' 'A' 72.0]
 ['George' 45 65 89 'C' 'C' 66.33333333333333]
 ['James' 64 32 26 'C' 'C' 40.666666666666664]
 ['Jade' 23 78 47 'F' 'F' 49.333333333333336]
 ['Tommy' 45 98 14 'C' 'C' 52.333333333333336]
 ['Yonus' 78 45 44 'A' 'A' 55.666666666666664]
 ['Randy' 95 12 84 'A' 'A' 63.666666666666664]
 ['Rex' 31 95 98 'F' 'F' 74.66666666666667]
 ['Tucsan' 77 32 56 'A' 'A' 55.0]
 ['Amell' 87 78 34 'A' 'A' 66.33333333333333]
 ['Vin' 65 45 78 'B' 'B' 62.666666666666664]
 ['Hector' 32 12 78 'F' 'F' 40.666666666666664]]


In [54]:
np.save('new-dataset',dataset)

In [56]:
np.savetxt("dataset-new.csv",dataset,delimiter=",")

TypeError: Mismatch between array dtype ('object') and format specifier ('%.18e,%.18e,%.18e,%.18e,%.18e,%.18e,%.18e')

In [57]:
df=pd.DataFrame(data=dataset)
print(df)

           0   1   2   3  4  5          6
0       John  45  22  98  C  C       55.0
1    William  44  23   2  S  S       23.0
2      Henry  22  89  35  F  F  48.666667
3      Chris  88  55  23  A  A  55.333333
4       Jack  45  89  45  C  C  59.666667
5   Stephane  64  45  48  C  C  52.333333
6     Harald  12  12  12  F  F       12.0
7     Hearmy  78  94  65  A  A       79.0
8     Sinsel  98  95  23  A  A       72.0
9     George  45  65  89  C  C  66.333333
10     James  64  32  26  C  C  40.666667
11      Jade  23  78  47  F  F  49.333333
12     Tommy  45  98  14  C  C  52.333333
13     Yonus  78  45  44  A  A  55.666667
14     Randy  95  12  84  A  A  63.666667
15       Rex  31  95  98  F  F  74.666667
16    Tucsan  77  32  56  A  A       55.0
17     Amell  87  78  34  A  A  66.333333
18       Vin  65  45  78  B  B  62.666667
19    Hector  32  12  78  F  F  40.666667


In [66]:
df=pd.DataFrame(data=dataset,columns=["name","maths","phy","chem","m-grade","p-grade","c-grade","avg"])
print(df)



ValueError: Shape of passed values is (20, 7), indices imply (20, 8)