In [1]:
import numpy as np

array1 = [[11,12,13,14],
          [22,23,24,25],
          [33,34,35,36]]

array1_new = np.array(array1)
print(array1_new)

[[11 12 13 14]
 [22 23 24 25]
 [33 34 35 36]]


In [2]:
x=[1,2,3,4]

array2=np.array(x)
print(array2)

[1 2 3 4]


shape and ndim


In [3]:
print(array1_new.ndim)

2


In [4]:
print(array1_new.shape)

(3, 4)


np.arrange() and np.resize()

In [5]:
print(array1_new)

[[11 12 13 14]
 [22 23 24 25]
 [33 34 35 36]]


In [6]:
print(array1_new.shape)

(3, 4)


In [7]:
array2=array1_new.reshape(4,3)
print(array2)

[[11 12 13]
 [14 22 23]
 [24 25 33]
 [34 35 36]]


In [8]:
array2=array1_new.reshape(6,2)
print(array2)

[[11 12]
 [13 14]
 [22 23]
 [24 25]
 [33 34]
 [35 36]]


In [9]:
array2=array1_new.reshape(1,12)
print(array2)

[[11 12 13 14 22 23 24 25 33 34 35 36]]


In [10]:
array=np.arange(-10,10,2)
print(array,array.ndim,array.shape)

[-10  -8  -6  -4  -2   0   2   4   6   8] 1 (10,)


In [11]:
array1=array.reshape(-1,1)
print(array1)

[[-10]
 [ -8]
 [ -6]
 [ -4]
 [ -2]
 [  0]
 [  2]
 [  4]
 [  6]
 [  8]]


In [12]:
array1=array.reshape(1,-1)
print(array1)

[[-10  -8  -6  -4  -2   0   2   4   6   8]]


Array Creation Routines

In [13]:
import numpy as np
x = np.empty((3,2),dtype = int)
print(x)

[[21955344541417551 23362702244839490]
 [22236849581981791 19703656396554307]
 [22236883941785665                82]]


In [14]:
x = np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [15]:
x = np.zeros((5,3),dtype = float)
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
x = np.zeros((5,3),dtype = float)
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
x = np.ones((5,3),dtype = float)
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Indexing & Slicing

In [18]:
array=np.random.randint(0,100,(10,5))
print(array)

[[ 6  4 41 53 20]
 [99 65  5  8 29]
 [33 45 49 95 23]
 [91 63 68 54 58]
 [79 95 58 97 81]
 [94 93 14 76 15]
 [16 80 18 44  4]
 [32 23  5 68 27]
 [58 37 98 17 84]
 [76 62 36 20 47]]


In [19]:
array1=np.random.randint(0,100,(4,3))
array2=np.random.randint(0,100,(4,3))

array3 = array1 + array2
print('array1:',array1)
print('array2:',array2)
print('array3:',array3)

array1: [[78 24  9]
 [14 66 45]
 [65 27 90]
 [93 13 20]]
array2: [[16 64  5]
 [65  1  6]
 [72 91 39]
 [96  8 70]]
array3: [[ 94  88  14]
 [ 79  67  51]
 [137 118 129]
 [189  21  90]]


In [20]:
array1=np.random.randint(0,100,(4,3))

array2=array1/10

print('array1:',array1)
print('array2:',array2)

array1: [[55 71 63]
 [12 77 58]
 [75 72 85]
 [30 16 95]]
array2: [[5.5 7.1 6.3]
 [1.2 7.7 5.8]
 [7.5 7.2 8.5]
 [3.  1.6 9.5]]


In [21]:
array1=np.random.randint(0,100,(4,3))
array2=np.random.randint(0,100,(3,5))

print('array1:',array1)
print('array2:',array2)

array4=np.matmul(array1,array2)

print('array4:',array4)

array1: [[ 8 41 29]
 [35 23 44]
 [67 81 83]
 [16 62 66]]
array2: [[32 37 62 56 95]
 [52 22 91 66 67]
 [33 53 81 18 26]]
array4: [[ 3345  2735  6576  3676  4261]
 [ 3768  4133  7827  4270  6010]
 [ 9095  8660 18248 10592 13950]
 [ 5914  5454 11980  6176  7390]]


In [22]:
array=np.random.randint(0,100,(5,7))
print(array)

[[45 43 85 12 93 29 92]
 [33 45 91 88 35 42 99]
 [54 62 83 50 45 80 16]
 [53 81 12  5 79 69 48]
 [29 54 66 41 30 68 47]]


In [23]:
print(np.max(array))

99


In [24]:
print(np.argmax(array))

13


In [25]:
print(np.max(array,axis=0))

[54 81 91 88 93 80 99]


In [26]:
print(np.argmax(array,axis=0))

[2 3 1 1 0 2 1]


In [27]:
print(np.max(array,axis=1))

[93 99 83 81 68]


In [28]:
print(np.argmax(array,axis=1))

[4 6 2 1 5]


In [29]:
array=np.random.randint(0,100,(5,10))
print(array)

[[53 33 36 17 63 98 71 86 13 47]
 [25 20 91  7 65  1  1 83 32 28]
 [91 75 20 70 53 33 90 96 14 99]
 [92 49 60 24 71 61 51 42 16 31]
 [97 19 46 26 99 33 78 33 58  5]]


In [30]:
print(array[2,3])

70


In [31]:
print(array[0:2,0:4])

[[53 33 36 17]
 [25 20 91  7]]


In [32]:
print(array[:,0:4])

[[53 33 36 17]
 [25 20 91  7]
 [91 75 20 70]
 [92 49 60 24]
 [97 19 46 26]]


In [33]:
print(array[:,4])

[63 65 53 71 99]


In [34]:
print(array[:2,:])

[[53 33 36 17 63 98 71 86 13 47]
 [25 20 91  7 65  1  1 83 32 28]]


In [37]:
import pandas as pd

dataset=pd.read_csv('student-marks.csv')

In [38]:
print(dataset)

        Name  Maths  Physics  Chemistry
0       John     45       22         98
1    William     44       23          2
2      Henry     22       89         35
3      Chris     88       55         23
4       Jack     45       89         45
5   Stephane     64       45         48
6     Harald     12       12         12
7     Hearmy     78       94         65
8     Sinsel     98       95         23
9     George     45       65         89
10     James     64       32         26
11      Jade     23       78         47
12     Tommy     45       98         14
13     Yonus     78       45         44
14     Randy     95       12         84
15       Rex     31       95         98
16    Tucsan     77       32         56
17     Amell     87       78         34
18       Vin     65       45         78
19    Hector     32       12         78


In [39]:
dataset=pd.read_csv('student-marks.csv').values
print(dataset)

[['John' 45 22 98]
 ['William' 44 23 2]
 ['Henry' 22 89 35]
 ['Chris' 88 55 23]
 ['Jack' 45 89 45]
 ['Stephane' 64 45 48]
 ['Harald' 12 12 12]
 ['Hearmy' 78 94 65]
 ['Sinsel' 98 95 23]
 ['George' 45 65 89]
 ['James' 64 32 26]
 ['Jade' 23 78 47]
 ['Tommy' 45 98 14]
 ['Yonus' 78 45 44]
 ['Randy' 95 12 84]
 ['Rex' 31 95 98]
 ['Tucsan' 77 32 56]
 ['Amell' 87 78 34]
 ['Vin' 65 45 78]
 ['Hector' 32 12 78]]
