In [1]:
import numpy as np

array1 = [[11,12,13,14],
          [22,23,24,25],
          [33,34,35,36]]

array1_new = np.array(array1)
print(array1_new)

[[11 12 13 14]
 [22 23 24 25]
 [33 34 35 36]]


In [2]:
x=[1,2,3,4]

array2=np.array(x)
print(array2)

[1 2 3 4]


shape and ndim


In [3]:
print(array1_new.ndim)

2


In [5]:
print(array1_new.shape)

(3, 4)


np.arrange() and np.resize()

In [11]:
print(array1_new)

[[11 12 13 14]
 [22 23 24 25]
 [33 34 35 36]]


In [12]:
print(array1_new.shape)

(3, 4)


In [14]:
array2=array1_new.reshape(4,3)
print(array2)

[[11 12 13]
 [14 22 23]
 [24 25 33]
 [34 35 36]]


In [15]:
array2=array1_new.reshape(6,2)
print(array2)

[[11 12]
 [13 14]
 [22 23]
 [24 25]
 [33 34]
 [35 36]]
