In [1]:
import numpy as np

array1 = [[11,12,13,14],
          [22,23,24,25],
          [33,34,35,36]]

array1_new = np.array(array1)
print(array1_new)

[[11 12 13 14]
 [22 23 24 25]
 [33 34 35 36]]


In [2]:
x=[1,2,3,4]

array2=np.array(x)
print(array2)

[1 2 3 4]


shape and ndim


In [3]:
print(array1_new.ndim)

2


In [5]:
print(array1_new.shape)

(3, 4)


np.arrange() and np.resize()

In [11]:
print(array1_new)

[[11 12 13 14]
 [22 23 24 25]
 [33 34 35 36]]


In [12]:
print(array1_new.shape)

(3, 4)


In [14]:
array2=array1_new.reshape(4,3)
print(array2)

[[11 12 13]
 [14 22 23]
 [24 25 33]
 [34 35 36]]


In [15]:
array2=array1_new.reshape(6,2)
print(array2)

[[11 12]
 [13 14]
 [22 23]
 [24 25]
 [33 34]
 [35 36]]


In [16]:
array2=array1_new.reshape(1,12)
print(array2)

[[11 12 13 14 22 23 24 25 33 34 35 36]]


In [20]:
array=np.arange(-10,10,2)
print(array,array.ndim,array.shape)

[-10  -8  -6  -4  -2   0   2   4   6   8] 1 (10,)


In [24]:
array1=array.reshape(-1,1)
print(array1)

[[-10]
 [ -8]
 [ -6]
 [ -4]
 [ -2]
 [  0]
 [  2]
 [  4]
 [  6]
 [  8]]


In [25]:
array1=array.reshape(1,-1)
print(array1)

[[-10  -8  -6  -4  -2   0   2   4   6   8]]


Array Creation Routines

In [28]:
import numpy as np
x = np.empty((3,2),dtype = int)
print(x)

[[25895968444448860 23925768161198147]
 [32370111954616435 23925729506951260]
 [31525476570497107 32651513914720368]]


In [29]:
x = np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [30]:
x = np.zeros((5,3),dtype = float)
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [31]:
x = np.zeros((5,3),dtype = float)
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [32]:
x = np.ones((5,3),dtype = float)
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Indexing & Slicing

In [33]:
array=np.random.randint(0,100,(10,5))
print(array)

[[15 19 18 12 76]
 [74 20 91 37 95]
 [76 57 84 29 82]
 [29 82 57 13 98]
 [93 95 61 62  6]
 [74 39 37 14  3]
 [64 97  4 61 33]
 [94 64  9 81 44]
 [59 90 23  9 29]
 [48 88 28 85 76]]


In [35]:
array1=np.random.randint(0,100,(4,3))
array2=np.random.randint(0,100,(4,3))

array3 = array1 + array2
print('array1:',array1)
print('array2:',array2)
print('array3:',array3)

array1: [[84 86 25]
 [66 66 11]
 [85 85 80]
 [20 14  8]]
array2: [[70 86 44]
 [71 25 90]
 [48 95 46]
 [30 92  7]]
array3: [[154 172  69]
 [137  91 101]
 [133 180 126]
 [ 50 106  15]]


In [36]:
array1=np.random.randint(0,100,(4,3))

array2=array1/10

print('array1:',array1)
print('array2:',array2)

array1: [[98 47 53]
 [17 99 59]
 [82 21 91]
 [97 70 61]]
array2: [[9.8 4.7 5.3]
 [1.7 9.9 5.9]
 [8.2 2.1 9.1]
 [9.7 7.  6.1]]


In [37]:
array1=np.random.randint(0,100,(4,3))
array2=np.random.randint(0,100,(3,5))

print('array1:',array1)
print('array2:',array2)

array4=np.matmul(array1,array2)

print('array4:',array4)

array1: [[61 75 11]
 [50 12 92]
 [81 24 70]
 [89 65 98]]
array2: [[30 82 25 13 57]
 [70 95 44 41 13]
 [53 89 47 86 40]]
array4: [[ 7663 13106  5342  4814  4892]
 [ 7216 13428  6102  9054  6686]
 [ 7820 15152  6371  8057  7729]
 [12414 22195  9691 12250  9838]]
