1 Opencv Basics

How to load a image

In [8]:
import cv2 #importing opencv module

img = cv2.imread(r"C:\Users\ASUS\OneDrive\Desktop\python new\codes\new-flower.png")
#print(img.shape,img.ndim,type(img))

img[:,100:110]=[0,255,255]

cv2.imshow('LIVE',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
img=cv2.imread(r"C:\Users\ASUS\OneDrive\Desktop\python new\codes\new-flower.png")

img[100:150,100:200]=[0,255,255]

cv2.imshow('IMG',img)
cv2.waitKey(2000)
cv2.destroyAllWindows()

How to load a video file

In [7]:
import cv2

source=cv2.VideoCapture(r"C:\Users\ASUS\OneDrive\Desktop\python new\codes\Samples\road_drive.avi")

while(True):
   ret,img=source.read()
   print(ret)

   if(ret==False):
       break

   cv2.imshow('IMG',img)
   key=cv2.waitKey(1)

   if(key==27):
      break
   elif(key==112):
       cv2.waitKey(0)

cv2.destroyAllWindows()

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


Point Operators(Pixelwise Operations)

Color Conversion

In [34]:
img1=cv2.imread(r"C:\Users\ASUS\OneDrive\Desktop\python new\codes\new-flower.png",0)
img2=cv2.imread(r"C:\Users\ASUS\OneDrive\Desktop\python new\codes\new-flower.png",1)
img3=cv2.imread(r"C:\Users\ASUS\OneDrive\Desktop\python new\codes\new-flower.png",-1)

cv2.imshow('IMG1',img1)
cv2.imshow('IMG2',img2)
cv2.imshow('IMG3',img3)

cv2.waitKey(0)
cv2.destroyAllWindows()


Changing Colorspaces

In [35]:
import numpy as np

array=np.random.randint(0,255,(3,5))
print(array)
print('---------------------------------------')
array_new=np.mean(array,axis=1)
print(array_new)

[[ 10 192  53  57  58]
 [120 173 183 234 102]
 [223 115  62   0 209]]
---------------------------------------
[ 74.  162.4 121.8]


In [40]:
def myCvtColor(img):
    img_new=np.mean(img,axis=2)
    img_new=np.array(img_new,dtype=np.uint8)
    print(img.shape,img_new.shape)
    return img_new

In [41]:
img=cv2.imread(r"C:\Users\ASUS\OneDrive\Desktop\python new\codes\new-flower.png")
transformed=myCvtColor(img)

cv2.imshow('transformed',transformed)

cv2.waitKey(0)
cv2.destroyAllWindows()

(361, 480, 3) (361, 480)


In [39]:
img=cv2.imread(r"C:\Users\ASUS\OneDrive\Desktop\python new\codes\new-flower.png")
gray=cv2.cvtColor(img,cv2.COLOR_BGR2HSV)

cv2.imshow('IMG',img)
cv2.imshow('GRAY',gray)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [21]:
img=cv2.imread(r"C:\Users\ASUS\OneDrive\Desktop\python new\codes\new-flower.png")
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
hsv=cv2.cvtColor(img,cv2.COLOR_BGR2HSV)

cv2.imshow('IMG',img)
cv2.imshow('GRAY',gray)
cv2.imshow('HSV',hsv)

cv2.waitKey(0)
cv2.destroyAllWindows()

Image Thresholding